#pragma once

namespace SmashEngine
{
	enum CameraSignal{ CAMERA_UP, CAMERA_DOWN, CAMERA_LEFT, CAMERA_RIGHT, CAMERA_ZOOMIN, CAMERA_ZOOMOUT, CAMERA_ROTATE_LEFT, CAMERA_ROTATE_RIGHT, CAMERA_ROTATE_UP, CAMERA_ROTATE_DOWN};
}